name: Back merge from main to dev

on:
  pull_request_target:
    branches: [main]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge-main-back-to-dev:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'hotfix/')
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Git config
      run: |
          git config --local user.email "42103905+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
    
    - name: Merge main back to dev
      run: |
          git fetch --unshallow
          git switch dev
          git pull
          git merge --no-ff main -m "Auto-merge main back to dev"
          git push
